version: '2.1'

services:
  mongodb:
    image: mongo:2.4
    container_name: mongodb
    ports:
     - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  config:
    image: dockerpinguin/demo-complaints-config
    container_name: config
    ports:
     - "8888:8888"
    environment:
     - SPRING_PROFILES_ACTIVE=production
  discovery:
    image: dockerpinguin/demo-complaints-discovery
    container_name: discovery
    ports:
     - "8761:8761"
